services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      # BLOB エンドポイント
      - "10000:10000"
      # キュー エンドポイント
      - "10001:10001"
      # テーブル エンドポイント
      - "10002:10002"
    volumes:
      - azurite-data:/data

  azure-cli:
    image: mcr.microsoft.com/azure-cli
    tty: true
    volumes:
      - ./examples:/examples

volumes:
  azurite-data: